### ISSUE TITLE
Not able to disable the view interactions

### ISSUE THREAD

**Issue by shahdhiren** [liufengting/FTIndicator#4]
Hi,

I am using the FTProgressIndicator from cocoapods version 1.1. I want to disable the view interaction in some of the screen while progress indicator is going on. But I can see that there are currently no API available to disable the view interaction.

Are there any plan to include such APIs? Let me know if any alternatives are available apart from handling within app?

Thanks & Regards,

**Comment by liufengting** [comment]
I will add this feather in this two days.

**Comment by liufengting** [comment]
https://github.com/liufengting/FTIndicator/blob/master/ChangeLog.md

I just added disable user interaction support in Pod version 1.1.3, check it out. If you find any bugs, please let me know. : )

**Comment by shahdhiren** [comment]
@liufengting 💯 👍 Thanks and you saved my days... 
Just a thought if as a FTProgressIndicator library when userInteractionEnable property is kept false, should a library disables the keyboard as well by calling `self.view.endEditing(false)`??

**Comment by liufengting** [comment]
Here is how to get the current view controller.
http://stackoverflow.com/questions/24825123/get-the-current-view-controller-from-the-app-delegate）

However, I will not add this function to this library, because I think It's better for developers to decide wether to dismiss keyboard, not progress hud, like you are doing in your project. Of course, you are welcome to try it in you own project.
